### ISSUE TITLE
Use const generics for number of parameters

### ISSUE THREAD

**Issue by sophie-h** [n1m3/linregress#4]
I'm not sure if this could work, but it could imagine that there could be added compile safety for accessing the parameter etc with rustc 1.51?

**Comment by n1m3** [comment]
Hmm, as far as I know nalgebra and ndarray don't currently support const generics, so this would probably be limited to replacing the `Vecs` in `RegressionParameters` with arrays, right?

I'd like there to still be a way to use the library if you *don't* know the number of parameters at compile time,
so this would probably get a little too complex to be worth it at the moment.

Cool idea though, especially since this would prevent trying to access non existent parameters at compile time!
